### ISSUE TITLE
Append not working with Dask > 2.1.0

### ISSUE THREAD

**Issue by SteffenNa** [ranaroussi/pystore#21]
Append stopped working for me in 0.1.12

My reproducible example:

```
import random
import datetime as dt
import pandas as pd
import pystore as ps

#create df with random numbers and timestamp as index
n = 2
timestamps = [dt.datetime.utcnow() + dt.timedelta(seconds=x) for x in range(n)]
pb = ([{'timestamp': timestamp, 'pb': random.random()} for timestamp in timestamps])
df = pd.DataFrame.from_dict(pb).set_index('timestamp')

store = ps.store('mydatastore') 
collection = store.collection('eod')

#write to pystore
collection.write('symbol', df[:-1], overwrite=True)

#append to pystore
collection.append('symbol',  df[-1:]) 

#read 
collection.item('symbol').to_pandas()
```
This works in 0.1.9
Would be grateful for any hint.

Kind regards
Steffen

**Comment by cevans3098** [comment]
Steffen,

I have been using 0.1.12 without any issues.  I ran your code and it worked fine.  Do you have any errors you can share?

Craig

**Comment by SteffenNa** [comment]
Hi Craig
Thanks for your message and checking. Really spooky. Fails without complaining when I try to append. No traceback whatsoever.
Will have another look.
Cheers
Steffen

**Comment by SteffenNa** [comment]
I just did a clean new install of Miniconda and it still doesn't work. pip freeze gives me:
```
appnope==0.1.0
asn1crypto==0.24.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
bokeh==1.3.2
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.1
conda==4.7.10
conda-package-handling==1.3.11
cryptography==2.7
Cython==0.29.12
cytoolz==0.10.0
dask==2.2.0
decorator==4.4.0
defusedxml==0.6.0
distributed==2.2.0
entrypoints==0.3
fastparquet==0.3.0
fsspec==0.4.0
heapdict==1.0.0
idna==2.8
ipykernel==5.1.1
ipython==7.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.0
jedi==0.13.3
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
libarchive-c==2.8
llvmlite==0.29.0
locket==0.2.0
MarkupSafe==1.1.1
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
msgpack==0.6.1
multitasking==0.0.9
nbconvert==5.5.0
nbformat==4.4.0
notebook==6.0.0
numba==0.45.0
numpy==1.16.4
olefile==0.46
packaging==19.0
pandas==0.25.0
pandocfilters==1.4.2
parso==0.5.0
partd==1.0.0
patsy==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
psutil==5.6.3
ptyprocess==0.6.0
pycosat==0.6.3
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrsistent==0.14.11
PySocks==1.7.0
PyStore==0.1.12
python-dateutil==2.8.0
python-snappy==0.5.4
pytz==2019.1
PyYAML==5.1.1
pyzmq==18.0.0
qtconsole==4.5.2
requests==2.22.0
ruamel-yaml==0.15.46
scikit-learn==0.21.2
scipy==1.3.0
Send2Trash==1.5.0
six==1.12.0
sortedcontainers==2.1.0
statsmodels==0.10.1
tblib==1.4.0
terminado==0.8.2
testpath==0.4.2
thrift==0.11.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.32.1
traitlets==4.3.2
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.0
zict==1.0.0
```
has to be something else that goes wrong

**Comment by cevans3098** [comment]
I'm running on windows 10, with Python 3.6 with Anaconda3
some of the relevant modules I have running
dask==1.2.2
fastparquet==0.3.0
PyStore==0.1.12
pandas==0.25.0

Does your collection get written and the first item also created?  just the append fails?  have you tried deleting the collection file and rerunning your code

The only update Ran did to the append method was in 0.1.10 where he allowed for both the partition and chuncksize to be changed.  He also updated the Pandas requirement to 0.25.0

maybe roll back to 0.1.10 and ensure that works

**Comment by SteffenNa** [comment]
I will do more investigating indeed. Its just the append that fails. Deleted collection and even tried with new store. Suspect the culprit is dask or fastparquet. 0.1.10 doesn't do it either.
Thanks again for your help! Much appreciated

**Comment by SteffenNa** [comment]
Update: Works with Dask 2.1.0 and PyStore 0.1.12. So the culprit is Dask 2.2. 
Thanks again for your help Craig!!!

**Comment by SteffenNa** [comment]
Update: just tried with `dask==2.3.0` to no avail. Append works fine with `dask<=2.1.0`. @ranaroussi would be great if you could take a look

**Comment by ranaroussi** [comment]
I've pushed a new version to the dev branch. It should result in a faster and more consistent behavior when using append. By default, PyStore will aim for partitions of ~99MB each (as per Dask's recommendation).

LMK.

**Comment by SteffenNa** [comment]
Just gave it a spin with `dask==2.3.0` in my system. Append still doesn't appear to work.

**Comment by ranaroussi** [comment]
I’m running Dask 2.2.0. I’ll need to run a test using 2.3.0 to confirm. 

Can you confirm that you’re using PyStore 0.1.13 from the dev branch?

**Comment by SteffenNa** [comment]
Yes. Was using the new code from collection.py.

**Comment by ranaroussi** [comment]
After digging (A LOT) I discovered that there's an issue with Dask 2.3.0 + fastparquet and/or numba. Whenever I used `collection.write()` or `collection.append()`, the script failed.

If you're using Anaconda - try runinng `conda update numba` and you'll see Dask being downgraded to 2.1.0 for compatbility.

You can either wait for the fastparqet team to fix the issue, or use a temp fix I discovered, which is importing `numba` (which, apparently, is used by fastparquet) before importing `pystore`. 

So...

```python

import numba
import pystore

import yfinance as yf
df = yf.download("MSFT")

store = pystore.store('test')
collection = store.collection('msft')

collection.write(ds, df[:5000])

for x in range(5001, len(df)):
    collection.append('msft', df[x:x+1])
```

This worked for me using:
- `pystore 0.1.13`
- `dask 2.3.0`
- `fastparquet 0.3.2`
- `numba 0.45.1`

LMK

**Comment by ranaroussi** [comment]
Please read this regarding Dask 2.3.0:
https://github.com/ranaroussi/pystore/issues/21#issuecomment-523467142

**Comment by SteffenNa** [comment]
Thanks a lot for this Ran. The sheer number of dependencies Dask installs always made me a little uncomfortable TBH. However since Dask is support by the Anaconda team I didn't worry too much. Am using `numba==0.45.1` in my system for option pricing anyway. So will check this out tomorrow.

**Comment by ranaroussi** [comment]
I don't know if this is an issue with `fastparquet`, `numba` (used by `fastparquet`), or the `llvm` engine (used by `numba`) - but I was able to work around this issue by importing `numba` in `PyStore`'s `__init__.py`.

I've also added optimized default partitioning that aims for ~99MB partitions (as per Dask best practices section) and the ability to specify the engine you'd like to use for your datastore, giving you the option to choose between `pystore.store('name', engine='fastparquet')` or `pystore.store('name', engine='pyarrow')`.

LMK

**Comment by SteffenNa** [comment]
Thanks for the update. `pystore==0.1.13` works for me with `dask==2.1.0`. (not with any of the two ewer versions).
other relevant packages:
`fastparquet==0.3.0`
`numba==0.45.1`
Lets soo what these Dask+Fastparquet guys come up with. Suppose you did not report anything to them?

**Comment by ranaroussi** [comment]
Can you try upgrading to fastparquet 0.3.2?

I'm running using the following without problems now (thanks to the `import numba` part in `pystore`'s `__init__.py`):

- `pystore 0.1.13`
- `dask 2.3.0`
- `fastparquet 0.3.2`
- `numba 0.45.1`

**Comment by SteffenNa** [comment]
will try. newest version on conda channel is `0.3.0`. will do pip install --upgrade which gets me `0.3.2`. Will most probably get back on Monday on this.

**Comment by SteffenNa** [comment]
Just gave it a spin with `fastparquet==0.3.2` and 'dask==2.3.0` and it works. Happy we can put this to rest. Have a great weekend!
